services:
  
  query-script:
    image: node:14
    working_dir: /app
    command: sleep infinity
    volumes:
      - ./query-script:/app

    secrets:
      - mynamePostgres_pas
    
    env_file: ./env/dev.env
    environment:
      Db_HOST: db
  
  db:
    image: postgres
    volumes:
      - "./db:/docker-entrypoint-initdb.d"

    secrets:
      - mynamePostgres_pas

    env_file: ./env/dev.env
    
    ports:
      - "5432:5432"

secrets:
  mynamePostgres_pas:
   file: "./secrets/aaaa"

    
